# Generated by Django 6.0.2 on 2026-03-01 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_fetched', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=20)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=300)),
                ('source_url', models.CharField(blank=True, max_length=800)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, db_index=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('posted_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('is_remote', models.BooleanField(db_index=True, null=True)),
                ('workplace_type', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_min', models.FloatField(blank=True, null=True)),
                ('salary_max', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('salary_text', models.CharField(blank=True, max_length=300, null=True)),
                ('apply_url', models.CharField(blank=True, max_length=800, null=True)),
                ('company_logo', models.CharField(blank=True, max_length=800, null=True)),
                ('extracted_skills', models.JSONField(default=list)),
                ('seniority', models.CharField(blank=True, db_index=True, max_length=50)),
                ('job_type', models.CharField(blank=True, max_length=50)),
                ('uid', models.CharField(db_index=True, max_length=600, unique=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-first_seen'],
            },
        ),
    ]
