# Generated by Django 6.0.2 on 2026-03-12 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySkillAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField()),
                ('total_mentions', models.IntegerField()),
                ('num_snapshots', models.IntegerField(default=1)),
                ('avg_mentions', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['skill_name', 'date'], name='jobs_dailys_skill_n_786eb6_idx')],
                'unique_together': {('skill_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SkillSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('mention_count', models.IntegerField()),
                ('total_jobs', models.IntegerField(help_text='Total jobs in this scrape cycle')),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['skill_name', 'scraped_at'], name='jobs_skills_skill_n_11f94d_idx')],
            },
        ),
    ]
